# Generated by Django 6.1.1 on 2026-10-01 14:41

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import examdesk.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Clarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('wording', models.TextField(blank=True)),
                ('closed_reason', models.CharField(blank=True, choices=[('announced', 'Announced'), ('merged', 'Merged')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='examdesk.answer')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='examdesk.clarification')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='clarification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='examdesk.clarification'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instructor_token', models.CharField(default=examdesk.models.new_token, max_length=64, unique=True)),
                ('ta_token', models.CharField(default=examdesk.models.new_token, max_length=64, unique=True)),
                ('is_live', models.BooleanField(default=True)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clarification',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarifications', to='examdesk.exam'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=30)),
                ('text', models.TextField()),
                ('by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clarification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='examdesk.clarification')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='examdesk.exam')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=30)),
                ('seat', models.CharField(max_length=30)),
                ('text', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to=examdesk.models.photo_path)),
                ('by', models.CharField(max_length=100)),
                ('client_key', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clarification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='examdesk.clarification')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('ta', 'TA'), ('instructor', 'Instructor')], max_length=20)),
                ('venue', models.CharField(blank=True, max_length=30, null=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='examdesk.exam')),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('exam'), django.db.models.functions.text.Lower('name'), name='one_member_per_name')],
            },
        ),
        migrations.CreateModel(
            name='Readout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=30)),
                ('by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readouts', to='examdesk.announcement')),
            ],
            options={
                'ordering': ['venue'],
                'constraints': [models.UniqueConstraint(fields=('announcement', 'venue'), name='one_readout_per_venue')],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='examdesk.answer')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='examdesk.report')),
            ],
            options={
                'verbose_name_plural': 'deliveries',
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('report', 'answer'), name='one_delivery_per_answer')],
            },
        ),
        migrations.CreateModel(
            name='SeatClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=30)),
                ('seat', models.CharField(max_length=30)),
                ('by', models.CharField(max_length=100)),
                ('claimed_at', models.DateTimeField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='examdesk.exam')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exam', 'venue', 'seat'), name='one_claim_per_seat')],
            },
        ),
    ]
